@startuml
[-> GpsKafkaConsumerListener: Kafka消息
note left GpsKafkaConsumerListener: 消息消费
activate GpsKafkaConsumerListener
GpsKafkaConsumerListener -> DeviceStream :stream
activate DeviceStream
DeviceStream->DeviceController :onLoadCtx
activate DeviceController
DeviceStream->DeviceController:execute

DeviceController -> DeviceController : onEvent
activate DeviceController
deactivate DeviceController

note right DeviceController
判断事件处理方式
    1.开始事件
    2.GPS事件
    3.事件
end note

alt event type start

'开始事件
DeviceController -> TjTrackFlowLayerImpl: onTrackStart
activate TjTrackFlowLayerImpl
note right TrackService
如果当前不是开始信号
先添加结束信号
end note
TjTrackFlowLayerImpl->TrackService:normalTrackEnd
activate TrackService
TrackService->TrackService :trackEndWithSegmentEnd
activate TrackService
TrackService->TrackAccumulateTimeControl:control
note left TrackAccumulateTimeControl
计算堵车时长
end note
activate TrackAccumulateTimeControl
TrackAccumulateTimeControl->TrackAccumulateTimeControl :getTrackTime
note right TrackAccumulateTimeControl
计算行程时间
1. 去除前后100米,抛出起步和熄火时间
2. 添加市内或者城际行车时间
end note
activate TrackAccumulateTimeControl
deactivate TrackAccumulateTimeControl
TrackAccumulateTimeControl--> TrackService:trackSegmentTime
deactivate TrackAccumulateTimeControl
TrackService->TrackService:calTjScore
activate TrackService
TrackService->TrackScoreControl:control
note right TrackService
计算单个行程的市内
或者城际积分
end note
activate TrackScoreControl
TrackScoreControl-->TrackService :result
deactivate TrackScoreControl
TrackService->DrawControl : control
note right TrackService
1. 离线不统计积分
2. 抽签结果判断是否加倍
end note
note left TrackService
1. 数据保存操作
2. 事件发送
3. 报告中心处理
end note
activate DrawControl
DrawControl-->TrackService :trackScore
deactivate DrawControl
deactivate TrackService
deactivate TrackService
deactivate TrackService

TjTrackFlowLayerImpl-->DeviceController : boolean
deactivate TjTrackFlowLayerImpl

else event type end
'结束事件
DeviceController -> TjTrackFlowLayerImpl: onTrackEnd
activate TjTrackFlowLayerImpl
TjTrackFlowLayerImpl->TrackService:normalTrackEnd
activate TrackService
TrackService->TrackService :trackEndWithSegmentEnd
activate TrackService
TrackService->TrackAccumulateTimeControl:control
activate TrackAccumulateTimeControl
TrackAccumulateTimeControl->TrackAccumulateTimeControl :getTrackTime
activate TrackAccumulateTimeControl
deactivate TrackAccumulateTimeControl
TrackAccumulateTimeControl--> TrackService:trackSegmentTime
deactivate TrackAccumulateTimeControl
TrackService->TrackService:calTjScore
activate TrackService
TrackService->TrackScoreControl:control
activate TrackScoreControl
TrackScoreControl-->TrackService :result
deactivate TrackScoreControl
TrackService->DrawControl : control
activate DrawControl
DrawControl-->TrackService :trackScore
deactivate DrawControl
deactivate TrackService
deactivate TrackService
deactivate TrackService
deactivate TrackService
deactivate TjTrackFlowLayerImpl
TjTrackFlowLayerImpl-->DeviceController :boolean
deactivate TjTrackFlowLayerImpl

else event type gps
'GPS事件
DeviceController -> TjTrackFlowLayerImpl: onUpload
note right DeviceController
1.加载行程上下文
为空补行程上下文
2. 根据行程上下文
加载段上下文
end note
activate TjTrackFlowLayerImpl
TjTrackFlowLayerImpl->TjSegmentJob :run
activate TjSegmentJob
note right TjSegmentJob
过滤无效点,进行存储
end note

TjSegmentJob->TjSegmentLayer :gpsPrepare
activate TjSegmentLayer
activate TjGpsPropertiesConstructorImpl
TjSegmentLayer->TjGpsPropertiesConstructorImpl: setDistanceProperties
activate TjGpsPropertiesConstructorImpl
TjSegmentLayer->TjGpsPropertiesConstructorImpl: setLocationProperties
TjGpsPropertiesConstructorImpl->TjGpsPropertiesConstructorImpl : set200MGpsLocationInfo
activate TjGpsPropertiesConstructorImpl
TjGpsPropertiesConstructorImpl->TjGpsPropertiesConstructorImpl : calculateEdgeSpeed
activate TjGpsPropertiesConstructorImpl
TjGpsPropertiesConstructorImpl-->TjSegmentLayer
deactivate TjGpsPropertiesConstructorImpl
deactivate TjGpsPropertiesConstructorImpl
deactivate TjGpsPropertiesConstructorImpl
deactivate TjGpsPropertiesConstructorImpl

TjSegmentLayer-->TjSegmentJob
deactivate TjSegmentLayer



activate TjSegmentJob
TjSegmentJob->TjSegmentJob:updateTrackProperties
activate TjSegmentJob
TjSegmentJob->TjSegmentJob:setTrackProperties
TjSegmentJob->TjSegmentJob:setTrackProperties
TjSegmentJob->TjSegmentJob:setTrackProperties

deactivate TjSegmentJob
deactivate TjSegmentJob

TjSegmentJob->TjSegmentLayer : segmentCal
activate TjSegmentLayer
TjSegmentLayer->TjGpsPropertiesConstructorImpl : cal

activate TjGpsPropertiesConstructorImpl
TjGpsPropertiesConstructorImpl->TjGpsPropertiesConstructorImpl : dealWithWhenSegmentStart
note right TjGpsPropertiesConstructorImpl
1.如果当前点和下一个点都大于临界速度
   1.1 上一次处理的最后一个gps 点是堵车点，并且当前处理的是包的第一个点
        1.1.1 如果上一个堵车段最后一个点和当前点时间小于时间限制条件并且距离小于距离限制条件，当前点任务是属于上一个堵车段，堵车段拼接
        1.1.2堵车段截断
    1.2 当前点加入到未确定的非堵车段
2.当前点速度小于等于临界速度或者下一个点小于等于临界速度
    2.1一个堵车段分在两个不同的批次处理
        2.1.1堵车段截断
        2.1.2同一个堵车段
    2.2堵车段截断
end note
activate TjGpsPropertiesConstructorImpl
TjGpsPropertiesConstructorImpl-->TjSegmentLayer : boolean
TjSegmentLayer --> TjSegmentJob

TjSegmentJob->TjSegmentJob:afterSegmentCal
activate TjSegmentJob
deactivate TjSegmentJob

deactivate TjGpsPropertiesConstructorImpl
deactivate TjGpsPropertiesConstructorImpl

deactivate TjSegmentLayer



TjSegmentJob-->TjTrackFlowLayerImpl : boolean
deactivate TjSegmentJob

TjTrackFlowLayerImpl--> DeviceController :boolean
deactivate TjTrackFlowLayerImpl
end



activate TjTrackFlowLayerImpl
'更新设备信息
DeviceController -> DeviceController : uploadCtx
activate DeviceController
deactivate DeviceController
deactivate DeviceController

DeviceStream-->GpsKafkaConsumerListener
deactivate DeviceStream
deactivate GpsKafkaConsumerListener

@enduml
